/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import controller.Controller;
import domain.object.entities.Student;
import domain.object.entities.StudentskiCentar;
import domain.object.entities.Uplatnica;
import domain.object.entities.Valuta;
import forms.models.ModelTabeleUplatnica;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Kristina
 */
public class UplatnicaForm extends javax.swing.JFrame {

    List<Uplatnica> uplatnice = new LinkedList<>();
    List<Uplatnica> pronadjenaUplatnica = new LinkedList<>();
    List<StudentskiCentar> studentskiCentri = new LinkedList<>();
    List<StudentskiCentar> pronadjeniCentri = new LinkedList<>();
    List<Student> studenti = new LinkedList<>();
    List<Valuta> valute = new LinkedList<>();

    HashMap<Integer, String[]> orinalneVrednosti = new HashMap<>();

    /**
     * Creates new form UplatnicaForm
     */
    public UplatnicaForm() throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        ModelTabeleUplatnica mtu = new ModelTabeleUplatnica(Controller.getInstance().getAllUplatnica());
        tblUplatnica.setModel(mtu);
        ucitajPodatkeUComboBox();
        setUpTableListener();
        sacuvajOriginalneVrednosti(tblUplatnica);
        setUpListenerNaCMB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUplatnica = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUplatnicaId = new javax.swing.JTextField();
        txtDatum = new javax.swing.JTextField();
        txtIznos = new javax.swing.JTextField();
        txtPozivNaBroj = new javax.swing.JTextField();
        txtSifraPlacanja = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtMesto = new javax.swing.JTextField();
        txtRacunPlatioca = new javax.swing.JTextField();
        txtRacunPrimaoca = new javax.swing.JTextField();
        txtSvrhaUplate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNazivCentra = new javax.swing.JTextField();
        cmbStudent = new javax.swing.JComboBox();
        cmbSCentar = new javax.swing.JComboBox();
        cmbValuta = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblUplatnica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Uplatnica id", "Datum", "Iznos", "Naziv studentskog centra", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tblUplatnica);

        jButton1.setText("izmeni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Uplatnica");

        txtPozivNaBroj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPozivNaBrojActionPerformed(evt);
            }
        });

        jLabel2.setText("Datum");

        jLabel3.setText("Uplatnica id");

        jLabel4.setText("Iznos");

        jLabel5.setText("Poziv na broj");

        jLabel6.setText("Sifra placanja");

        jLabel7.setText("Student");

        jLabel8.setText("Model");

        jLabel9.setText("Studentski centar");

        jLabel10.setText("Racun platioca");

        jLabel11.setText("Racun primaoca");

        jLabel12.setText("Svrha uplate");

        jLabel13.setText("Mesto");

        jButton2.setText("sacuvaj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setText("Valuta");

        jLabel15.setText("Naziv studentskog centra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 797, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txtIznos, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txtPozivNaBroj, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txtSifraPlacanja, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txtModel, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txtUplatnicaId)
                            .addComponent(cmbValuta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNazivCentra, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRacunPrimaoca, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRacunPlatioca, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSvrhaUplate, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                            .addComponent(cmbStudent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(cmbSCentar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUplatnicaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRacunPlatioca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRacunPrimaoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPozivNaBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSvrhaUplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSifraPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cmbStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(cmbSCentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNazivCentra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(cmbValuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            ModelTabeleUplatnica mtu = (ModelTabeleUplatnica) tblUplatnica.getModel();
            Uplatnica u = mtu.getUplatnice().get(tblUplatnica.getSelectedRow());

            String setClause = generisiSetClause(tblUplatnica, tblUplatnica.getSelectedRow());

            Controller.getInstance().updateUplatnica(u, setClause);

            mtu.osvezi();
        } catch (Exception ex) {
            Logger.getLogger(UplatnicaForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPozivNaBrojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPozivNaBrojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPozivNaBrojActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            Uplatnica u = preuzmiPodatke();

            Controller.getInstance().insertUplatnica(u);

            ModelTabeleUplatnica mtu = (ModelTabeleUplatnica) tblUplatnica.getModel();
            mtu.osvezi();
        } catch (Exception ex) {
            Logger.getLogger(UplatnicaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UplatnicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UplatnicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UplatnicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UplatnicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UplatnicaForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(UplatnicaForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbSCentar;
    private javax.swing.JComboBox cmbStudent;
    private javax.swing.JComboBox cmbValuta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUplatnica;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtIznos;
    private javax.swing.JTextField txtMesto;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtNazivCentra;
    private javax.swing.JTextField txtPozivNaBroj;
    private javax.swing.JTextField txtRacunPlatioca;
    private javax.swing.JTextField txtRacunPrimaoca;
    private javax.swing.JTextField txtSifraPlacanja;
    private javax.swing.JTextField txtSvrhaUplate;
    private javax.swing.JTextField txtUplatnicaId;
    // End of variables declaration//GEN-END:variables

    private void ucitajPodatkeUComboBox() throws Exception {
        ucitajStudentskiCentar();
        ucitajStudente();
        ucitajValute();
    }

    private void ucitajStudentskiCentar() throws Exception {
        studentskiCentri = Controller.getInstance().getAllStudentskiCentar();
        if (cmbSCentar != null) {
            cmbSCentar.removeAllItems();
            for (StudentskiCentar sc : studentskiCentri) {
                cmbSCentar.addItem(sc);
            }
        }
        cmbSCentar.setSelectedItem(null);
    }

    private void ucitajStudente() throws Exception {
        studenti = Controller.getInstance().getAllStudent();
        if (cmbStudent != null) {
            cmbStudent.removeAllItems();
            for (Student s : studenti) {
                cmbStudent.addItem(s);
            }
        }
        cmbStudent.setSelectedItem(null);

    }

    private void ucitajValute() throws Exception {
        valute = Controller.getInstance().getAllValuta();
        if (cmbValuta != null) {
            cmbValuta.removeAllItems();
            for (Valuta v : valute) {
                cmbValuta.addItem(v);
            }
        }
        cmbValuta.setSelectedItem(null);
    }

    private void popuniFormuIzabranomUplatnicom(Uplatnica izbranaUplatnica) {
        if (izbranaUplatnica != null) {
            txtUplatnicaId.setText(String.valueOf(izbranaUplatnica.getUplatnicaId()));
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            if (izbranaUplatnica.getDatum() == null) {
                txtDatum.setText(null);
            } else {
                txtDatum.setText(dateFormat.format(izbranaUplatnica.getDatum()));

            }

            txtIznos.setText(String.valueOf(izbranaUplatnica.getIznos()));
            txtPozivNaBroj.setText(String.valueOf(izbranaUplatnica.getPozivNaBroj()));
            txtSifraPlacanja.setText(String.valueOf(izbranaUplatnica.getSifraPlacanja()));
            txtModel.setText(String.valueOf(izbranaUplatnica.getModel1()));
            cmbValuta.setSelectedItem(izbranaUplatnica.getValuta());

            txtMesto.setText(izbranaUplatnica.getMesto());
            txtRacunPlatioca.setText(izbranaUplatnica.getRacunPlatioca());
            txtRacunPrimaoca.setText(izbranaUplatnica.getRacunPrimaoca());
            txtSvrhaUplate.setText(izbranaUplatnica.getSvrhaUplate());

            cmbSCentar.setSelectedItem(izbranaUplatnica.getSc());
            cmbStudent.setSelectedItem(izbranaUplatnica.getStudent());

        }

    }

    private void setUpTableListener() {
        tblUplatnica.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    if (tblUplatnica.getSelectedRow() >= 0) {
                        ModelTabeleUplatnica mtu = (ModelTabeleUplatnica) tblUplatnica.getModel();
                        Uplatnica izbranaUplatnica = mtu.getUplatnice().get(tblUplatnica.getSelectedRow());
                        popuniFormuIzabranomUplatnicom(izbranaUplatnica);
                    } else {
                        cleanCode();
                    }

                }
            }

        });
    }

    private void cleanCode() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void sacuvajOriginalneVrednosti(JTable tblUplatnica) {
        ModelTabeleUplatnica mtu = (ModelTabeleUplatnica) tblUplatnica.getModel();

        for (int i = 0; i < mtu.getRowCount(); i++) {
            Long scid = (Long) mtu.getValueAt(i, 3);
            String nazivsc = (String) mtu.getValueAt(i, 4);

            orinalneVrednosti.put(i, new String[]{String.valueOf(scid), nazivsc});
            System.out.println(orinalneVrednosti.get(0)[0]);

            System.out.println(orinalneVrednosti.get(0)[1]);
        }

    }

    private void ucitajNazivSC(StudentskiCentar scid) throws Exception {
        pronadjeniCentri = Controller.getInstance().findCentar("scid=" + scid.getScId() + "");
        txtNazivCentra.setText(pronadjeniCentri.get(0).getNaziv());
    }

    private void setUpListenerNaCMB() {
        cmbSCentar.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    try {
                        ucitajNazivSC((StudentskiCentar) cmbSCentar.getSelectedItem());
                    } catch (Exception ex) {
                    }
                }
            }

        });
    }

    private String generisiSetClause(JTable tblUplatnica, int selectedRow) {
        ModelTabeleUplatnica mtu = (ModelTabeleUplatnica) this.tblUplatnica.getModel();
        StringBuilder stringBuilder = new StringBuilder(" ");

        Long scid = (Long) mtu.getValueAt(selectedRow, 3);
        String nazivSC = (String) mtu.getValueAt(selectedRow, 4);

        String scidStr = String.valueOf(scid);

        String[] original = orinalneVrednosti.get(selectedRow);
        String orgSCID = original[0];
        String orgNaziv = original[1];

        boolean needComma = false;

        if (!scidStr.equals(orgSCID)) {
            System.out.println("poredimo sad '" + scidStr + "' sa '" + orgSCID + "'");
            stringBuilder.append("scid = '").append(scid).append("'");
            needComma = true;
        }
        if (!nazivSC.equals(orgNaziv)) {
            System.out.println("poredim '" + nazivSC + "' sa '" + orgNaziv + "'");
            if (needComma) {
                stringBuilder.append(", ");
            }
            stringBuilder.append("naziv_sc = '").append(nazivSC).append("'");
        }
        return stringBuilder.toString();

    }

    private Uplatnica preuzmiPodatke() {
        SimpleDateFormat inputFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = null;
        String datum = txtDatum.getText();

        if (!datum.isEmpty()) {
            try {
                date = inputFormat.parse(datum);
            } catch (ParseException ex) {
                Logger.getLogger(UplatnicaForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Long id = Long.parseLong(txtUplatnicaId.getText());
        int isnos = Integer.parseInt(txtIznos.getText());
        int pozivNaBroj = Integer.parseInt(txtPozivNaBroj.getText());
        int sifra = Integer.parseInt(txtSifraPlacanja.getText());
        int model = Integer.parseInt(txtModel.getText());

        Uplatnica u = new Uplatnica(id, date, isnos, pozivNaBroj,
                sifra, txtMesto.getText(),
                model, txtRacunPlatioca.getText(), txtRacunPrimaoca.getText(),
                txtSvrhaUplate.getText(), (StudentskiCentar) cmbSCentar.getSelectedItem(),
                (Student) cmbStudent.getSelectedItem(), (Valuta) cmbValuta.getSelectedItem(), "");

        return u;
    }
}
